site_name: 皆の意見交流所サーバー公式ホームページ
site_url: https://linuxcodevserver.github.io/
theme:
    custom_dir: overrides
    name: material
    language: ja
    features:
        - navigation.indexes
        - navigation.tabs
        - navigation.tabs.sticky
        - search.suggest
        - search.highlight
        - search.share
        - header.autohide
        - navigation.top
        - toc.integrate
    palette:
        - scheme: default
          primary: teal
          accent: teal
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: teal
          accent: teal
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    icon:
        repo: fontawesome/brands/github
repo_name: linuxcodevserver/linuxcodevserver.github.io
repo_url: https://github.com/linuxcodevserver/linuxcodevserver.github.io
edit_uri: ""

nav:
    - Home: index.md
    - Projects: a_projects.md
    - Donate: donate.md
    - Blog:
        - Index: blogs.md
        - Tag Index: tags.md
        - Write: write.md

plugins:
    - blog:
        format: "(%Y/%m/%d)"
        text-align: "right"
    - search:
        lang:
            - en
            - ja
    - tags:
        tags_folder: docs/
        tags_template: tags.md.template
    - responsive-image
extra:
      analytics:
        - provider: google
          property: G-Z4J13YP1PJ
      disqus: linuxcodevserver
      social: 
        - icon: fontawesome/brands/discord
          link: https://discord.com/invite/sUdAE64Zc7
        - icon: https://toppng.com/uploads/preview/mattermost-logo-11609368489plncpdfdq9.png
          link: http://linuxcodevserver.ddns.net:6896/

markdown_extentions:
    - codehilite:
        noclasses: true
        pygments_style: colorful
        linenums: true
    - pymdownx.superfences
    - footnotes
copyright: This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License. To view a copy of this license, visit
http://creativecommons.org/licenses/by-sa/4.0/.
