site_name: 皆の意見交流所サーバー公式ホームページ

theme:
    custom_dir: overrides
    name: material
    language: ja
    features:
        - navigation.indexes
        - navigation.tabs
        - navigation.tabs.sticky
    palette:
        - scheme: default
          primary: indigo
          accent: blue
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: red
          accent: orange
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
repo_name: linuxcodevserver/linuxcodevserver.github.io
repo_url: https://github.com/linuxcodevserver/linuxcodevserver.github.io
edit_uri: ""

plugins:
    - blog:
        format: "(%Y/%m/%d)"
        text-align: "right"
        articles: 5
        display-article-date: False
