name: bloglist updater

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest # 最新のubuntu環境で下記のジョブを実行
    steps:
      - uses: actions/checkout@v2 # おまじない
      - name: Add Blog Title and Categories and Description and Author to index.md
        run: |
          cat << "EOF" > docs/blogs.md
          ---
          title: ブログ一覧 
          description: ブログ一覧
          ---
          <h1>ブログ一覧</h1>
          EOF
          cat bloglist | tr '\n' ' ' > bloglist-fixed
          for filename in $(cat bloglist-fixed)
            do
            echo $filename
            url=$(echo ${filename} | sed "s/docs\///g" | sed "s/.md//g")
            url="https://linuxcodevserver.github.io/${url}"
            echo "url :$url"
            title=$(cat $filename | grep "title: " | sed "s/title:\ //g")
            echo "title: $title"
            echo '<a href="'$url'"><h2>'"${title}"'</h2></a>' >> docs/blogs.md
            categories=$(cat $filename | grep "categories: " | sed -e "s/categories:\ //g")
            author=$(cat $filename | grep "author: " | sed "s/author:\ //g")
            echo "categories: $categories"
            echo "author: $author"
            description=$(cat $filename | grep "description: " | sed "s/description:\ //g")
            echo "<span><b>${categories}</b></span>" >> docs/blogs.md
            echo "<span>${author}</span>"
            echo '<p style="width: 70%, height: 70%; color: gray;">'"${description}"'</p>' >> docs/blogs.md
            echo "description: $description"
            done
          rm bloglist-fixed

      - name: Commit and Push # 実行した結果をプッシュして変更をレポジトリに反映
        run: |
          git config user.name "Github Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "[update] bloglist.md"
          git pull
          git push origin master
