name: MkDocs

on:
  push:
    branches:
      - master
    paths:
      - mkdocs.yml
      - docs/**
      - custom_dir/**
      - overrides/**
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          sleep 5s # wait for bloglist updater
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git fetch origin gh-pages
          
      - name: Install MkDocs
        run: |
          python3 -m pip install setuptools
          python3 -m pip install -r requirements.txt
          git clone https://github.com/facelessuser/pymdown-extensions/
          cd pymdown-extensions
          python3 setup.py build
          python3 setup.py install
          
      - name: Deploy HTML files
        run: python3 -m mkdocs gh-deploy
